"""empty message

Revision ID: a3e05acff3a7
Revises: d18d517d2431
Create Date: 2016-11-24 21:50:33.402266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e05acff3a7'
down_revision = 'd18d517d2431'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('minute', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'minute')
    ### end Alembic commands ###
